#!/usr/bin/env php
<?php

const BASE_PATH = __DIR__ . DIRECTORY_SEPARATOR;

//if (file_exists(BASE_PATH . 'down')) {
//    echo 'Application is under maintenance mode.';
//
//    exit(1);
//}

/** @noinspection PhpNoReturnAttributeCanBeAddedInspection */
function dd(...$args): void
{
    var_dump(...$args);

    die();
}

// Composer autoloader
require BASE_PATH . 'vendor/autoload.php';

// Error reporting tool
(new NunoMaduro\Collision\Provider)->register();

$application = new Symfony\Component\Console\Application();

$application->setName('Laravel Framework');
$application->setVersion('12.0.0');

$commands = array_map(function ($filename) {
    $class = basename($filename, '.php');

    $class = "Rovshen\\Console\\Commands\\$class";

    return new $class;
}, glob(__DIR__ . '/src/Commands/*'));

$application->addCommands($commands);

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();

    exit(1);
}