#!/usr/bin/env php
<?php

use Rovshen\Console\Commands\InspireCommand;

const BASE_PATH = __DIR__ . DIRECTORY_SEPARATOR;

/** @noinspection PhpNoReturnAttributeCanBeAddedInspection */
function dd(...$args): void
{
    var_dump(...$args);

    die();
}

// Composer autoloader
require BASE_PATH . 'vendor/autoload.php';

// Error reporting tool
(new NunoMaduro\Collision\Provider)->register();

$application = new Symfony\Component\Console\Application();

$application->setName('Laravel Framework');
$application->setVersion('12.0.0');

$commands = [
    new InspireCommand()
];

$application->addCommands($commands);

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();
}